(define (problem TemperatureControl)
(:domain MaintainTemperature)
 (:objects Temp1 User_humid1 Sensor_humid1 User1 Sensor1)
 (:init (temp Temp1) (user_input User1) (user_input_humid User_humid1) (sensor_input_humid Sensor_humid1)(sensor_input Sensor1))
 (:goal (and (not(temp Temp1)) (user_input User1) (sensor_input Sensor1)(user_input_humid User_humid1) (sensor_input_humid Sensor_humid1)))
)
